# Generated by Django 5.2.7 on 2025-10-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('companyia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_lanzamiento', models.DateField()),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
